apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      nodeSelector:
          "beta.kubernetes.io/os": linux
      containers:
        - name: node-ci
          image: node-ci
          ports:
            - name: http
              containerPort: 1337