apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: default
images:
- name: node-ci
  newName: avik6028/node-ci
  newTag: 421230f88975251da056652f43aebe0366f2af77
