apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs
  name: nodejs
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 1337
  selector:
    app: nodejs
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs
  name: nodejs
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: avik6028/node-ci:421230f88975251da056652f43aebe0366f2af77
        name: node-ci
        ports:
        - containerPort: 1337
          name: http
      nodeSelector:
        beta.kubernetes.io/os: linux
